const item = '<dte:Item BienOServicio="B" NumeroLinea="$INDEX"><dte:Cantidad>$CANTIDAD</dte:Cantidad><dte:UnidadMedida>UNI</dte:UnidadMedida><dte:Descripcion>$DESCRIPCION</dte:Descripcion><dte:PrecioUnitario>$PUNIT</dte:PrecioUnitario><dte:Precio>$PTOTAL</dte:Precio><dte:Descuento>0.00</dte:Descuento><dte:Impuestos><dte:Impuesto><dte:NombreCorto>IVA</dte:NombreCorto><dte:CodigoUnidadGravable>1</dte:CodigoUnidadGravable><dte:MontoGravable>$MONTOSINIMPUESTO</dte:MontoGravable><dte:MontoImpuesto>%IMPUESTO</dte:MontoImpuesto></dte:Impuesto></dte:Impuestos><dte:Total>$PTOTAL</dte:Total></dte:Item>'

const clientData = '<?xml version="1.0" encoding="UTF-8"?><RetornaDatosClienteRequest><nit>$NIT</nit></RetornaDatosClienteRequest>'

const cancel = '<?xml version="1.0" encoding="UTF-8"?><AnulaDocumentoXMLRequest id="$UUID"><xml_dte><![CDATA[$DATA]]></xml_dte></AnulaDocumentoXMLRequest>'

const cancelSign = '<?xml version="1.0" encoding="UTF-8"?><FirmaDocumentoRequest id="$UUIDFA"><xml_dte><![CDATA[<?xml version="1.0" encoding="UTF-8"?><ns:GTAnulacionDocumento xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:ns="http://www.sat.gob.gt/dte/fel/0.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="0.1"><ns:SAT><ns:AnulacionDTE ID="DatosCertificados"><ns:DatosGenerales ID="DatosAnulacion" NumeroDocumentoAAnular="$UUIDDOCUMENTO" NITEmisor="684443K" IDReceptor="$NITRECEPTOR" FechaEmisionDocumentoAnular="$FECHADOCUMENTO" FechaHoraAnulacion="$FECHAANULACION" MotivoAnulacion="$MOTIVO"/></ns:AnulacionDTE></ns:SAT></ns:GTAnulacionDocumento>]]></xml_dte></FirmaDocumentoRequest>'

const registerBill = '<?xml version=\'1.0\' encoding=\'UTF-8\'?><RegistraDocumentoXMLRequest id="$UUID"><xml_dte><![CDATA[&FACTURA]]></xml_dte></RegistraDocumentoXMLRequest>'

const signBill = '<?xml version="1.0" encoding="UTF-8"?><FirmaDocumentoRequest id="$UUID"><xml_dte><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?><dte:GTDocumento xmlns:dte="http://www.sat.gob.gt/dte/fel/0.2.0" Version="0.1"><dte:SAT ClaseDocumento="dte"><dte:DTE ID="DatosCertificados"><dte:DatosEmision ID="DatosEmision"><dte:DatosGenerales CodigoMoneda="GTQ" FechaHoraEmision="$FECHA" Tipo="FACT"/><dte:Emisor AfiliacionIVA="GEN" CodigoEstablecimiento="1"  NITEmisor="120166550" NombreComercial="AGROPECUARIA ALDANA, SOCIEDAD ANÓNIMA" NombreEmisor="AGROPECUARIA ALDANA, SOCIEDAD ANÓNIMA"><dte:DireccionEmisor><dte:Direccion>BARRIO EL PORVENIR</dte:Direccion><dte:CodigoPostal>2001</dte:CodigoPostal><dte:Municipio>GUASTATOYA</dte:Municipio><dte:Departamento>EL PROGRESO</dte:Departamento><dte:Pais>GT</dte:Pais></dte:DireccionEmisor></dte:Emisor><dte:Receptor CorreoReceptor="$CORREO" IDReceptor="$NIT" NombreReceptor="$NOMBRE"><dte:DireccionReceptor><dte:Direccion>$DIRECCIONR</dte:Direccion><dte:CodigoPostal>$CODIGOPOSTALR</dte:CodigoPostal><dte:Municipio/><dte:Departamento/><dte:Pais>GT</dte:Pais></dte:DireccionReceptor></dte:Receptor><dte:Frases><dte:Frase CodigoEscenario="1" TipoFrase="1"/></dte:Frases><dte:Items>$ITEMS</dte:Items><dte:Totales><dte:TotalImpuestos><dte:TotalImpuesto NombreCorto="IVA" TotalMontoImpuesto="$TOTALI"/></dte:TotalImpuestos><dte:GranTotal>$TOTALV</dte:GranTotal></dte:Totales></dte:DatosEmision></dte:DTE></dte:SAT></dte:GTDocumento>]]></xml_dte></FirmaDocumentoRequest>'

const getPDF = '<?xml version="1.0" encoding="UTF-8"?><RetornaPDFRequest><uuid>$UUID</uuid></RetornaPDFRequest>'

export { item, clientData, cancel, cancelSign, registerBill, signBill, getPDF }
